// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file player_positions.proto (package player_positions, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file player_positions.proto.
 */
export const file_player_positions: GenFile = /*@__PURE__*/
  fileDesc("ChZwbGF5ZXJfcG9zaXRpb25zLnByb3RvEhBwbGF5ZXJfcG9zaXRpb25zIm4KDlBsYXllclBvc2l0aW9uEhEKCXVuaXF1ZV9pZBgBIAEoCRITCgtwbGF5ZXJfbmFtZRgCIAEoCRIJCgF6GAMgASgBEgkKAXkYBCABKAESCQoBeBgFIAEoARITCgt2ZWhpY2xlX2tleRgGIAEoCSJECg9QbGF5ZXJQb3NpdGlvbnMSMQoHcGxheWVycxgBIAMoCzIgLnBsYXllcl9wb3NpdGlvbnMuUGxheWVyUG9zaXRpb25iBnByb3RvMw");

/**
 * @generated from message player_positions.PlayerPosition
 */
export type PlayerPosition = Message<"player_positions.PlayerPosition"> & {
  /**
   * @generated from field: string unique_id = 1;
   */
  uniqueId: string;

  /**
   * @generated from field: string player_name = 2;
   */
  playerName: string;

  /**
   * @generated from field: double z = 3;
   */
  z: number;

  /**
   * @generated from field: double y = 4;
   */
  y: number;

  /**
   * @generated from field: double x = 5;
   */
  x: number;

  /**
   * @generated from field: string vehicle_key = 6;
   */
  vehicleKey: string;
};

/**
 * Describes the message player_positions.PlayerPosition.
 * Use `create(PlayerPositionSchema)` to create a new message.
 */
export const PlayerPositionSchema: GenMessage<PlayerPosition> = /*@__PURE__*/
  messageDesc(file_player_positions, 0);

/**
 * @generated from message player_positions.PlayerPositions
 */
export type PlayerPositions = Message<"player_positions.PlayerPositions"> & {
  /**
   * @generated from field: repeated player_positions.PlayerPosition players = 1;
   */
  players: PlayerPosition[];
};

/**
 * Describes the message player_positions.PlayerPositions.
 * Use `create(PlayerPositionsSchema)` to create a new message.
 */
export const PlayerPositionsSchema: GenMessage<PlayerPositions> = /*@__PURE__*/
  messageDesc(file_player_positions, 1);

