import { VehicleKey } from './player_positions_pb';

export function vehicleKeyToString(key: VehicleKey): string {
  switch (key) {
    case VehicleKey.VEHICLE_KEY_1:
      return '1';
    case VehicleKey.VEHICLE_KEY_2:
      return '2';
    case VehicleKey.VEHICLE_KEY_3:
      return '3';
    case VehicleKey.VEHICLE_KEY_4:
      return '4';
    case VehicleKey.VEHICLE_KEY_TUSCAN:
      return 'Tuscan';
    case VehicleKey.VEHICLE_KEY_KART_01:
      return 'Kart_01';
    case VehicleKey.VEHICLE_KEY_SCM_KART_ONE:
      return 'SCM_Kart_One';
    case VehicleKey.VEHICLE_KEY_DAFFY:
      return 'Daffy';
    case VehicleKey.VEHICLE_KEY_MICKY:
      return 'Micky';
    case VehicleKey.VEHICLE_KEY_STELLA:
      return 'Stella';
    case VehicleKey.VEHICLE_KEY_KOMA:
      return 'Koma';
    case VehicleKey.VEHICLE_KEY_TROPHY_TAXI:
      return 'Trophy_Taxi';
    case VehicleKey.VEHICLE_KEY_ELISA:
      return 'Elisa';
    case VehicleKey.VEHICLE_KEY_TAXI_01:
      return 'Taxi_01';
    case VehicleKey.VEHICLE_KEY_DUKE:
      return 'Duke';
    case VehicleKey.VEHICLE_KEY_CERVOS:
      return 'Cervos';
    case VehicleKey.VEHICLE_KEY_NIMO:
      return 'Nimo';
    case VehicleKey.VEHICLE_KEY_NIMO_TAXI:
      return 'Nimo_Taxi';
    case VehicleKey.VEHICLE_KEY_STAGON:
      return 'Stagon';
    case VehicleKey.VEHICLE_KEY_PANTHER:
      return 'Panther';
    case VehicleKey.VEHICLE_KEY_VISTA:
      return 'Vista';
    case VehicleKey.VEHICLE_KEY_ZINO:
      return 'Zino';
    case VehicleKey.VEHICLE_KEY_MAGIS:
      return 'Magis';
    case VehicleKey.VEHICLE_KEY_ESSAM:
      return 'Essam';
    case VehicleKey.VEHICLE_KEY_CORA:
      return 'Cora';
    case VehicleKey.VEHICLE_KEY_ENFOGT:
      return 'EnfoGT';
    case VehicleKey.VEHICLE_KEY_NEO:
      return 'Neo';
    case VehicleKey.VEHICLE_KEY_FORTEM:
      return 'Fortem';
    case VehicleKey.VEHICLE_KEY_ZYDRO:
      return 'Zydro';
    case VehicleKey.VEHICLE_KEY_SPORTS_01:
      return 'Sports_01';
    case VehicleKey.VEHICLE_KEY_FOX:
      return 'Fox';
    case VehicleKey.VEHICLE_KEY_MITAGE:
      return 'Mitage';
    case VehicleKey.VEHICLE_KEY_MUHAN:
      return 'Muhan';
    case VehicleKey.VEHICLE_KEY_POLICEINTERCEPTOR_01:
      return 'PoliceInterceptor_01';
    case VehicleKey.VEHICLE_KEY_ELISA_POLICE:
      return 'Elisa_Police';
    case VehicleKey.VEHICLE_KEY_POLICE_01:
      return 'Police_01';
    case VehicleKey.VEHICLE_KEY_MUHAN_POLICE:
      return 'Muhan_Police';
    case VehicleKey.VEHICLE_KEY_ZYDRO_POLICE:
      return 'Zydro_Police';
    case VehicleKey.VEHICLE_KEY_TOWNIE:
      return 'Townie';
    case VehicleKey.VEHICLE_KEY_TOWNIE_BUS:
      return 'Townie_Bus';
    case VehicleKey.VEHICLE_KEY_LILIPUT:
      return 'Liliput';
    case VehicleKey.VEHICLE_KEY_SCHOOLBUS_01:
      return 'SchoolBus_01';
    case VehicleKey.VEHICLE_KEY_BUS:
      return 'Bus';
    case VehicleKey.VEHICLE_KEY_DUMBI:
      return 'Dumbi';
    case VehicleKey.VEHICLE_KEY_CHEETAHMK1:
      return 'CheetahMk1';
    case VehicleKey.VEHICLE_KEY_PICKUP_02:
      return 'Pickup_02';
    case VehicleKey.VEHICLE_KEY_VOLTEX:
      return 'Voltex';
    case VehicleKey.VEHICLE_KEY_MAMMOTH:
      return 'Mammoth';
    case VehicleKey.VEHICLE_KEY_KIRA_FLATBED:
      return 'Kira_Flatbed';
    case VehicleKey.VEHICLE_KEY_KIRA_BOX:
      return 'Kira_Box';
    case VehicleKey.VEHICLE_KEY_KIRA_TANKER:
      return 'Kira_Tanker';
    case VehicleKey.VEHICLE_KEY_TRONKO:
      return 'Tronko';
    case VehicleKey.VEHICLE_KEY_GARBAGETRUCK_01:
      return 'GarbageTruck_01';
    case VehicleKey.VEHICLE_KEY_MIXERTRUCK_01:
      return 'MixerTruck_01';
    case VehicleKey.VEHICLE_KEY_SRT:
      return 'SRT';
    case VehicleKey.VEHICLE_KEY_SEMITRUCK_01:
      return 'SemiTruck_01';
    case VehicleKey.VEHICLE_KEY_TITAN:
      return 'Titan';
    case VehicleKey.VEHICLE_KEY_KUDA:
      return 'Kuda';
    case VehicleKey.VEHICLE_KEY_CAMPY:
      return 'Campy';
    case VehicleKey.VEHICLE_KEY_FORMULASCM:
      return 'FormulaSCM';
    case VehicleKey.VEHICLE_KEY_TROPHY_AIR:
      return 'Trophy_Air';
    case VehicleKey.VEHICLE_KEY_SAVANNAH:
      return 'Savannah';
    case VehicleKey.VEHICLE_KEY_DORY:
      return 'Dory';
    case VehicleKey.VEHICLE_KEY_JEMUSI:
      return 'Jemusi';
    case VehicleKey.VEHICLE_KEY_JEMUSI_TANKER:
      return 'Jemusi_Tanker';
    case VehicleKey.VEHICLE_KEY_JEMUSI_DUMP:
      return 'Jemusi_Dump';
    case VehicleKey.VEHICLE_KEY_JEMUSI_SEMI:
      return 'Jemusi_Semi';
    case VehicleKey.VEHICLE_KEY_LOBO:
      return 'Lobo';
    case VehicleKey.VEHICLE_KEY_BORA:
      return 'Bora';
    case VehicleKey.VEHICLE_KEY_DABO:
      return 'Dabo';
    case VehicleKey.VEHICLE_KEY_DUMPTRUCK_01:
      return 'DumpTruck_01';
    case VehicleKey.VEHICLE_KEY_ATLAS_8X4_DUMP:
      return 'Atlas_8x4_Dump';
    case VehicleKey.VEHICLE_KEY_ATLAS_6X2_TANKER:
      return 'Atlas_6x2_Tanker';
    case VehicleKey.VEHICLE_KEY_ATLAS_6X2_DRYVAN:
      return 'Atlas_6x2_Dryvan';
    case VehicleKey.VEHICLE_KEY_ATLAS_4X2_SEMI:
      return 'Atlas_4x2_Semi';
    case VehicleKey.VEHICLE_KEY_ATLAS_6X4_SEMI:
      return 'Atlas_6x4_Semi';
    case VehicleKey.VEHICLE_KEY_ATLAS_6X2_SEMI:
      return 'Atlas_6x2_Semi';
    case VehicleKey.VEHICLE_KEY_KUDA_LIVEFISHTANK_4X2:
      return 'Kuda_LiveFishTank_4x2';
    case VehicleKey.VEHICLE_KEY_KUDA_CONTAINER_6X2:
      return 'Kuda_Container_6x2';
    case VehicleKey.VEHICLE_KEY_KUDA_DRYVAN_4X2:
      return 'Kuda_Dryvan_4x2';
    case VehicleKey.VEHICLE_KEY_KUDA_FLATBED_4X2:
      return 'Kuda_Flatbed_4x2';
    case VehicleKey.VEHICLE_KEY_GOLIMA_SEMI:
      return 'Golima_Semi';
    case VehicleKey.VEHICLE_KEY_LONGHORN_SEMI:
      return 'Longhorn_Semi';
    case VehicleKey.VEHICLE_KEY_BRUTUS_TANKER:
      return 'Brutus_Tanker';
    case VehicleKey.VEHICLE_KEY_BONGO:
      return 'Bongo';
    case VehicleKey.VEHICLE_KEY_BONGO_BUS:
      return 'Bongo_Bus';
    case VehicleKey.VEHICLE_KEY_ROADMASTER:
      return 'Roadmaster';
    case VehicleKey.VEHICLE_KEY_TRAILER_FLANKER3:
      return 'Trailer_Flanker3';
    case VehicleKey.VEHICLE_KEY_TRAILER_FLANKER3S:
      return 'Trailer_Flanker3S';
    case VehicleKey.VEHICLE_KEY_TRAILER_COTRA_20_3:
      return 'Trailer_Cotra_20_3';
    case VehicleKey.VEHICLE_KEY_TRAILER_COTRA_20_3L:
      return 'Trailer_Cotra_20_3L';
    case VehicleKey.VEHICLE_KEY_TRAILER_COTRA_40_3:
      return 'Trailer_Cotra_40_3';
    case VehicleKey.VEHICLE_KEY_TRAILER_VAMOS3:
      return 'Trailer_Vamos3';
    case VehicleKey.VEHICLE_KEY_TRAILER_LOMAX:
      return 'Trailer_Lomax';
    case VehicleKey.VEHICLE_KEY_TRAILER_CARRY:
      return 'Trailer_Carry';
    case VehicleKey.VEHICLE_KEY_TRAILER_TANKO40:
      return 'Trailer_Tanko40';
    case VehicleKey.VEHICLE_KEY_TRAILER_EASTWOOD:
      return 'Trailer_Eastwood';
    case VehicleKey.VEHICLE_KEY_TRAILER_01:
      return 'Trailer_01';
    case VehicleKey.VEHICLE_KEY_TRAILER_9M_FLAT_01:
      return 'Trailer_9m_Flat_01';
    case VehicleKey.VEHICLE_KEY_TRAILER_30FT_LOG_01:
      return 'Trailer_30ft_Log_01';
    case VehicleKey.VEHICLE_KEY_TRAILER_30FT_TANKER_01:
      return 'Trailer_30ft_Tanker_01';
    case VehicleKey.VEHICLE_KEY_TRAILER_OLDUM:
      return 'Trailer_Oldum';
    case VehicleKey.VEHICLE_KEY_TRAILER_OLLOK:
      return 'Trailer_Ollok';
    case VehicleKey.VEHICLE_KEY_TRAILER_OLBE:
      return 'Trailer_Olbe';
    case VehicleKey.VEHICLE_KEY_TRAILER_SPT1:
      return 'Trailer_SPT1';
    case VehicleKey.VEHICLE_KEY_TRAILER_LOBOVAN:
      return 'Trailer_LoboVan';
    case VehicleKey.VEHICLE_KEY_TRAILER_BULKO:
      return 'Trailer_Bulko';
    case VehicleKey.VEHICLE_KEY_TRAILER_DOOLY_S1:
      return 'Trailer_Dooly_S1';
    case VehicleKey.VEHICLE_KEY_TRAILER_DOOLY_D1:
      return 'Trailer_Dooly_D1';
    case VehicleKey.VEHICLE_KEY_TRAILER_DOOLY_S2:
      return 'Trailer_Dooly_S2';
    case VehicleKey.VEHICLE_KEY_TRAILER_DOOLY_D2:
      return 'Trailer_Dooly_D2';
    case VehicleKey.VEHICLE_KEY_TRAILER_SHOVAN_7:
      return 'Trailer_Shovan_7';
    case VehicleKey.VEHICLE_KEY_TRAILER_SHOVAN_10:
      return 'Trailer_Shovan_10';
    case VehicleKey.VEHICLE_KEY_TRAILER_SHOBED_7:
      return 'Trailer_Shobed_7';
    case VehicleKey.VEHICLE_KEY_TRAILER_SHOBED_10:
      return 'Trailer_Shobed_10';
    case VehicleKey.VEHICLE_KEY_TRAILER_SHOTAN_7:
      return 'Trailer_Shotan_7';
    case VehicleKey.VEHICLE_KEY_TRAILER_SHOTAN_10:
      return 'Trailer_Shotan_10';
    case VehicleKey.VEHICLE_KEY_TRAILER_HOBBER_LEAD:
      return 'Trailer_Hobber_Lead';
    case VehicleKey.VEHICLE_KEY_TRAILER_HOBBER_REAR:
      return 'Trailer_Hobber_Rear';
    case VehicleKey.VEHICLE_KEY_TRAILER_FLABER_LEAD:
      return 'Trailer_Flaber_Lead';
    case VehicleKey.VEHICLE_KEY_TRAILER_FLABER_REAR:
      return 'Trailer_Flaber_Rear';
    case VehicleKey.VEHICLE_KEY_TRAILER_TABER_LEAD:
      return 'Trailer_Taber_Lead';
    case VehicleKey.VEHICLE_KEY_TRAILER_TABER_REAR:
      return 'Trailer_Taber_Rear';
    case VehicleKey.VEHICLE_KEY_TRAILER_CONTER_LEAD_20FT:
      return 'Trailer_Conter_Lead_20ft';
    case VehicleKey.VEHICLE_KEY_TRAILER_CONTER_REAR_20FT:
      return 'Trailer_Conter_Rear_20ft';
    case VehicleKey.VEHICLE_KEY_TRAILER_CONTER_LEAD_40FT:
      return 'Trailer_Conter_Lead_40ft';
    case VehicleKey.VEHICLE_KEY_TRAILER_CONTER_REAR_40FT:
      return 'Trailer_Conter_Rear_40ft';
    case VehicleKey.VEHICLE_KEY_TRAILER_SMALL_CAGE_01:
      return 'Trailer_Small_Cage_01';
    case VehicleKey.VEHICLE_KEY_TRAILER_MIDDLE_TANKER_01:
      return 'Trailer_Middle_Tanker_01';
    case VehicleKey.VEHICLE_KEY_TRAILER_DINY_FLATBED:
      return 'Trailer_Dinky_Flatbed';
    case VehicleKey.VEHICLE_KEY_TRAILER_DINY_DRYVAN:
      return 'Trailer_Dinky_Dryvan';
    case VehicleKey.VEHICLE_KEY_TRAILER_DINY_TANKER:
      return 'Trailer_Dinky_Tanker';
    case VehicleKey.VEHICLE_KEY_TROPHY2:
      return 'Trophy2';
    case VehicleKey.VEHICLE_KEY_NUKE:
      return 'Nuke';
    case VehicleKey.VEHICLE_KEY_NUKE_POLICE:
      return 'Nuke_Police';
    case VehicleKey.VEHICLE_KEY_NUKE_TAXI:
      return 'Nuke_Taxi';
    case VehicleKey.VEHICLE_KEY_PULSE:
      return 'Pulse';
    case VehicleKey.VEHICLE_KEY_MONARCH:
      return 'Monarch';
    case VehicleKey.VEHICLE_KEY_MONARCH_LIMO:
      return 'Monarch_Limo';
    case VehicleKey.VEHICLE_KEY_RAVEN:
      return 'Raven';
    case VehicleKey.VEHICLE_KEY_VAN_01:
      return 'Van_01';
    case VehicleKey.VEHICLE_KEY_BOXY:
      return 'Boxy';
    case VehicleKey.VEHICLE_KEY_TAVAN:
      return 'Tavan';
    case VehicleKey.VEHICLE_KEY_KIRA_VAN:
      return 'Kira_Van';
    case VehicleKey.VEHICLE_KEY_EVAN:
      return 'EVan';
    case VehicleKey.VEHICLE_KEY_SCOOTY:
      return 'Scooty';
    case VehicleKey.VEHICLE_KEY_GUNTHOO:
      return 'Gunthoo';
    case VehicleKey.VEHICLE_KEY_ZERO:
      return 'Zero';
    case VehicleKey.VEHICLE_KEY_GUNTHOO_POLICE:
      return 'Gunthoo_Police';
    case VehicleKey.VEHICLE_KEY_DORY_WRECKER:
      return 'Dory_Wrecker';
    case VehicleKey.VEHICLE_KEY_TOWTRUCK_01:
      return 'TowTruck_01';
    case VehicleKey.VEHICLE_KEY_KIRA_ROLLBACKTOW:
      return 'Kira_RollbackTow';
    case VehicleKey.VEHICLE_KEY_BRUTUS_WRECKER:
      return 'Brutus_Wrecker';
    case VehicleKey.VEHICLE_KEY_GOLIMAROTATOR:
      return 'GolimaRotator';
    case VehicleKey.VEHICLE_KEY_LONGHORN_ROLLBACK:
      return 'Longhorn_Rollback';
    case VehicleKey.VEHICLE_KEY_LONGHORN_ROLLBACK_UL:
      return 'Longhorn_Rollback_UL';
    case VehicleKey.VEHICLE_KEY_VULCAN:
      return 'Vulcan';
    case VehicleKey.VEHICLE_KEY_TERRA:
      return 'Terra';
    case VehicleKey.VEHICLE_KEY_BRUTUS_FIREENGINE:
      return 'Brutus_FireEngine';
    case VehicleKey.VEHICLE_KEY_AMBI:
      return 'Ambi';
    case VehicleKey.VEHICLE_KEY_TAVAN_AMBULANCE:
      return 'Tavan_Ambulance';
    case VehicleKey.VEHICLE_KEY_BRUTUS_AMBULANCE:
      return 'Brutus_Ambulance';
    case VehicleKey.VEHICLE_KEY_NONE:
    case VehicleKey.VEHICLE_KEY_UNSPECIFIED:
      return 'None';
  }
}
