name: 🔍 Check
permissions:
  contents: read
on:
  - workflow_call

env:
  PUBLIC_API_BASE: ${{ vars.PUBLIC_API_BASE }}
  PUBLIC_DISCORD_LINK: ${{ vars.PUBLIC_DISCORD_LINK }}
  PUBLIC_DISCORD_EVENT_BASE: ${{ vars.PUBLIC_DISCORD_EVENT_BASE }}
  PUBLIC_SEASON_NO: ${{ vars.PUBLIC_SEASON_NO }}
  PUBLIC_SEASON_START_DATE: ${{ vars.PUBLIC_SEASON_START_DATE }}
  PUBLIC_PATREON_LINK: ${{ vars.PUBLIC_PATREON_LINK }}
  PUBLIC_HOUSE_PRICE_MULTIPLIER: ${{ vars.PUBLIC_HOUSE_PRICE_MULTIPLIER }}

jobs:
  check:
    name: 🔍 Check
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v6

      - name: 🗃️ Install pnpm
        uses: pnpm/action-setup@v5

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: 📥 Download pakop artifact
        uses: actions/download-artifact@v8
        with:
          name: wasm-pkg
          path: wasm/pakop/pkg

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🗒️ Get Playwright browsers version
        id: playwright-version
        run: |
          VERSION=$(pnpm exec playwright install chromium --with-deps --only-shell --dry-run | grep "Chrome Headless Shell" | awk '{print $4}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: 🗒️ Fetch Playwright browsers cache
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: '~/.cache/ms-playwright'
          key: 'playwright-${{ runner.os }}-${{ runner.arch }}-${{ steps.playwright-version.outputs.version }}'
          restore-keys: playwright-${{ runner.os }}-${{ runner.arch }}-

      - name: 🗒️ Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium --with-deps --only-shell

      - name: 🔌 Generate protobuf types
        run: pnpm proto:generate

      - name: 🌐 Generate i18n
        run: pnpm paraglide:compile

      - name: 🎨 Lint code
        run: pnpm lint

      - name: 🔍 Type check
        run: pnpm check

      - name: 🧪 Run tests
        run: pnpm test
