name: 📢 Discord Notification
permissions:
  contents: read
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 📢 Run Discord notification
        uses: ASEAN-Motor-Club/discord-notify@main
        with:
          discord-webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
